# Generated by Django 3.1.2 on 2020-10-23 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('authorID', models.CharField(max_length=100)),
                ('photo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Suggestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('authorID', models.CharField(default=0, max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='categoryID',
        ),
        migrations.RemoveField(
            model_name='product',
            name='photo',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='product',
            name='reference',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='suggestionID_2',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='suggestionID_3',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='suggestionID',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
